import React from "react";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Linking,
  Share,
  Platform,
} from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useStore } from "../lib/store";
import { Card, Badge } from "../components/UI";
import { C, S, F, R, shadow, colorOpacity } from "../lib/theme";

function calcAge(dob: string): number {
  const birth = new Date(dob + "T12:00:00");
  const now = new Date();
  let age = now.getFullYear() - birth.getFullYear();
  const m = now.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) age--;
  return age;
}

function fmtDob(dob: string): string {
  return new Date(dob + "T12:00:00").toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function severityColor(severity: "mild" | "moderate" | "severe"): string {
  if (severity === "severe") return C.err;
  if (severity === "moderate") return C.warn;
  return C.ok;
}

export default function Emergency() {
  const router = useRouter();
  const patient = useStore((s) => s.patient);
  const allergies = useStore((s) => s.allergies);
  const conditions = useStore((s) => s.conditions);
  const meds = useStore((s) => s.meds);

  const activeConditions = conditions.filter(
    (c) => c.status === "active" || c.status === "managed"
  );
  const activeMeds = meds.filter((m) => m.status === "active");
  const age = patient.dateOfBirth ? calcAge(patient.dateOfBirth) : null;

  const buildShareText = (): string => {
    const lines: string[] = [
      "=== EMERGENCY MEDICAL INFORMATION ===",
      "",
      `Name: ${patient.firstName} ${patient.lastName}`,
      patient.dateOfBirth
        ? `DOB: ${fmtDob(patient.dateOfBirth)}${age !== null ? ` (Age ${age})` : ""}`
        : "",
      `Sex: ${patient.sex}`,
      `Blood Type: ${patient.bloodType ?? "Unknown"}`,
      "",
    ];

    if (allergies.length > 0) {
      lines.push("ALLERGIES:");
      allergies.forEach((a) =>
        lines.push(`  • ${a.substance} — ${a.reaction} [${a.severity.toUpperCase()}]`)
      );
      lines.push("");
    } else {
      lines.push("ALLERGIES: None known", "");
    }

    if (activeConditions.length > 0) {
      lines.push("ACTIVE CONDITIONS:");
      activeConditions.forEach((c) =>
        lines.push(`  • ${c.name}${c.icd10 ? ` (${c.icd10})` : ""}`)
      );
      lines.push("");
    }

    if (activeMeds.length > 0) {
      lines.push("ACTIVE MEDICATIONS:");
      activeMeds.forEach((m) =>
        lines.push(`  • ${m.name} ${m.dosage} — ${m.frequency}`)
      );
      lines.push("");
    }

    if (patient.emergencyContact) {
      const ec = patient.emergencyContact;
      lines.push(
        "EMERGENCY CONTACT:",
        `  ${ec.name} (${ec.relationship}) — ${ec.phone}`,
        ""
      );
    }

    if (patient.insurance) {
      lines.push(
        "INSURANCE:",
        `  ${patient.insurance}${patient.memberId ? ` | Member ID: ${patient.memberId}` : ""}`,
        ""
      );
    }

    lines.push("Generated by Second Opinion. Verify with clinician.");
    return lines.filter((l) => l !== undefined).join("\n");
  };

  const handleShare = async () => {
    try {
      await Share.share({ message: buildShareText(), title: "Emergency Medical Info" });
    } catch {
      // User cancelled or error — silently ignore
    }
  };

  const handleCall = (phone: string) => {
    const url = `tel:${phone.replace(/\D/g, "")}`;
    Linking.canOpenURL(url).then((ok) => {
      if (ok) Linking.openURL(url);
    });
  };

  return (
    <View style={st.root}>
      {/* Red header bar */}
      <View style={st.header}>
        <TouchableOpacity onPress={() => router.back()} style={st.backBtn} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
          <Ionicons name="arrow-back" size={22} color="#fff" />
        </TouchableOpacity>
        <View style={st.headerCenter}>
          <Ionicons name="shield-checkmark" size={22} color="#fff" style={{ marginRight: S.sm }} />
          <Text style={st.headerTitle}>Emergency Info</Text>
        </View>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView
        style={st.scroll}
        contentContainerStyle={st.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Critical Info */}
        <View style={[st.criticalCard, { backgroundColor: C.errBg, borderColor: colorOpacity('err', 19) }]}>
          <View style={st.criticalHeader}>
            <Ionicons name="person-circle" size={20} color={C.err} />
            <Text style={[st.criticalTitle, { color: C.err }]}>Critical Patient Info</Text>
          </View>
          <Text style={st.patientName}>
            {patient.firstName} {patient.lastName}
          </Text>
          {patient.dateOfBirth ? (
            <Text style={st.patientMeta}>
              DOB: {fmtDob(patient.dateOfBirth)}
              {age !== null ? `  ·  Age ${age}` : ""}
              {patient.sex ? `  ·  ${patient.sex}` : ""}
            </Text>
          ) : null}
          <View style={st.bloodTypeRow}>
            <View style={[st.bloodTypeBadge, { backgroundColor: colorOpacity('err', 9), borderColor: colorOpacity('err', 25) }]}>
              <Ionicons name="water" size={14} color={C.err} style={{ marginRight: 4 }} />
              <Text style={[st.bloodTypeText, { color: C.err }]}>
                Blood Type: {patient.bloodType ?? "Unknown"}
              </Text>
            </View>
          </View>
        </View>

        {/* Allergies */}
        <View style={[st.sectionCard, { backgroundColor: C.warnBg, borderColor: colorOpacity('warn', 19) }]}>
          <View style={st.sectionHeaderRow}>
            <Text style={[st.sectionTitle, { color: C.warn }]}>⚠ Allergies</Text>
          </View>
          {allergies.length === 0 ? (
            <Text style={st.noneText}>No known allergies</Text>
          ) : (
            allergies.map((a) => (
              <View key={a.id} style={st.allergyRow}>
                <View style={st.allergyLeft}>
                  <Text style={st.allergySubstance}>{a.substance}</Text>
                  <Text style={st.allergyReaction}>{a.reaction}</Text>
                </View>
                <Badge
                  label={a.severity}
                  color={severityColor(a.severity)}
                />
              </View>
            ))
          )}
        </View>

        {/* Active Conditions */}
        <Card style={st.plainCard}>
          <View style={st.sectionHeaderRow}>
            <Ionicons name="medical" size={16} color={C.t1} style={{ marginRight: S.sm }} />
            <Text style={st.sectionTitle}>Active Conditions</Text>
          </View>
          {activeConditions.length === 0 ? (
            <Text style={st.noneText}>No active conditions on record</Text>
          ) : (
            activeConditions.map((c) => (
              <View key={c.id} style={st.listRow}>
                <Ionicons name="ellipse" size={6} color={C.pri} style={st.dot} />
                <View style={st.listLeft}>
                  <Text style={st.listName}>{c.name}</Text>
                  {c.icd10 ? <Text style={st.listSub}>ICD-10: {c.icd10}</Text> : null}
                </View>
              </View>
            ))
          )}
        </Card>

        {/* Active Medications */}
        <Card style={st.plainCard}>
          <View style={st.sectionHeaderRow}>
            <Ionicons name="flask" size={16} color={C.t1} style={{ marginRight: S.sm }} />
            <Text style={st.sectionTitle}>Active Medications</Text>
          </View>
          {activeMeds.length === 0 ? (
            <Text style={st.noneText}>No active medications on record</Text>
          ) : (
            activeMeds.map((m) => (
              <View key={m.id} style={st.listRow}>
                <Ionicons name="ellipse" size={6} color={C.priLt} style={st.dot} />
                <View style={st.listLeft}>
                  <Text style={st.listName}>{m.name} {m.dosage}</Text>
                  <Text style={st.listSub}>{m.frequency}</Text>
                </View>
              </View>
            ))
          )}
        </Card>

        {/* Emergency Contact */}
        {patient.emergencyContact ? (
          <Card style={st.plainCard}>
            <View style={st.sectionHeaderRow}>
              <Ionicons name="call" size={16} color={C.t1} style={{ marginRight: S.sm }} />
              <Text style={st.sectionTitle}>Emergency Contact</Text>
            </View>
            <View style={st.ecRow}>
              <View style={st.ecInfo}>
                <Text style={st.listName}>{patient.emergencyContact.name}</Text>
                <Text style={st.listSub}>{patient.emergencyContact.relationship}</Text>
                <Text style={st.ecPhone}>{patient.emergencyContact.phone}</Text>
              </View>
              <TouchableOpacity
                style={st.callBtn}
                onPress={() => handleCall(patient.emergencyContact!.phone)}
                activeOpacity={0.8}
              >
                <Ionicons name="call" size={18} color="#fff" />
                <Text style={st.callBtnText}>Call</Text>
              </TouchableOpacity>
            </View>
          </Card>
        ) : null}

        {/* Insurance */}
        {patient.insurance ? (
          <Card style={st.plainCard}>
            <View style={st.sectionHeaderRow}>
              <Ionicons name="card" size={16} color={C.t1} style={{ marginRight: S.sm }} />
              <Text style={st.sectionTitle}>Insurance</Text>
            </View>
            <Text style={st.listName}>{patient.insurance}</Text>
            {patient.memberId ? (
              <Text style={st.listSub}>Member ID: {patient.memberId}</Text>
            ) : null}
          </Card>
        ) : null}

        {/* Footer note */}
        <View style={st.footerNote}>
          <Ionicons name="information-circle-outline" size={16} color={C.t3} />
          <Text style={st.footerText}>Show this screen to any medical professional</Text>
        </View>

        {/* Share button */}
        <TouchableOpacity style={st.shareBtn} onPress={handleShare} activeOpacity={0.85}>
          <Ionicons name="share-outline" size={20} color="#fff" style={{ marginRight: S.sm }} />
          <Text style={st.shareBtnText}>Share Emergency Info</Text>
        </TouchableOpacity>

        <View style={{ height: S.xxl }} />
      </ScrollView>
    </View>
  );
}

const st = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.bg,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: C.err,
    paddingTop: Platform.OS === "ios" ? 54 : 36,
    paddingBottom: S.lg,
    paddingHorizontal: S.lg,
    ...shadow,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  headerCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: F.lg,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: -0.3,
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: S.lg,
    paddingTop: S.xl,
  },
  criticalCard: {
    borderRadius: R.lg,
    padding: S.lg,
    marginBottom: S.md,
    borderWidth: 1,
    ...shadow,
  },
  criticalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: S.sm,
  },
  criticalTitle: {
    fontSize: F.sm,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginLeft: S.xs,
  },
  patientName: {
    fontSize: F.xxl,
    fontWeight: "800",
    color: C.t1,
    letterSpacing: -0.5,
    marginBottom: S.xs,
  },
  patientMeta: {
    fontSize: F.md,
    color: C.t2,
    marginBottom: S.md,
  },
  bloodTypeRow: {
    flexDirection: "row",
  },
  bloodTypeBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: S.md,
    paddingVertical: S.xs + 2,
    borderRadius: R.pill,
    borderWidth: 1,
  },
  bloodTypeText: {
    fontSize: F.sm,
    fontWeight: "700",
  },
  sectionCard: {
    borderRadius: R.lg,
    padding: S.lg,
    marginBottom: S.md,
    borderWidth: 1,
    ...shadow,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: S.md,
  },
  sectionTitle: {
    fontSize: F.md,
    fontWeight: "700",
    color: C.t1,
    letterSpacing: -0.2,
  },
  plainCard: {
    marginBottom: S.md,
  },
  noneText: {
    fontSize: F.md,
    color: C.t3,
    fontStyle: "italic",
  },
  allergyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: S.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.brd,
  },
  allergyLeft: {
    flex: 1,
    marginRight: S.md,
  },
  allergySubstance: {
    fontSize: F.md,
    fontWeight: "700",
    color: C.t1,
    marginBottom: 2,
  },
  allergyReaction: {
    fontSize: F.sm,
    color: C.t2,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: S.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.brdLt,
  },
  dot: {
    marginTop: 6,
    marginRight: S.sm,
  },
  listLeft: {
    flex: 1,
  },
  listName: {
    fontSize: F.md,
    fontWeight: "600",
    color: C.t1,
    marginBottom: 2,
  },
  listSub: {
    fontSize: F.sm,
    color: C.t2,
  },
  ecRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ecInfo: {
    flex: 1,
    marginRight: S.md,
  },
  ecPhone: {
    fontSize: F.sm,
    color: C.pri,
    fontWeight: "600",
    marginTop: 2,
  },
  callBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.ok,
    paddingHorizontal: S.md,
    paddingVertical: S.sm,
    borderRadius: R.pill,
    gap: S.xs,
  },
  callBtnText: {
    fontSize: F.sm,
    fontWeight: "700",
    color: "#fff",
  },
  footerNote: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: S.sm,
    paddingVertical: S.lg,
  },
  footerText: {
    fontSize: F.sm,
    color: C.t3,
    fontStyle: "italic",
  },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.err,
    borderRadius: R.md,
    paddingVertical: S.md + 2,
    paddingHorizontal: S.xl,
    minHeight: 52,
    ...shadow,
  },
  shareBtnText: {
    fontSize: F.md,
    fontWeight: "700",
    color: "#fff",
  },
});
